import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../../hooks';
import { useAuthStore } from '../../store';
import { ROUTES } from '../../../shared/constants';
import { adminService } from '../../../data/api/adminService';
import { teacherAuthService } from '../../../data/api/teacherAuthService';
import { motion, AnimatePresence } from 'framer-motion';

// Lucide Icons
import {
    Mail,
    Lock,
    Eye,
    EyeOff,
    Shield,
    GraduationCap,
    ArrowLeft,
    AlertCircle,
    CheckCircle2
} from 'lucide-react';

// Login type for the toggle
type LoginType = 'admin' | 'teacher';

export function AdminLoginPage() {
    const { isRTL } = useLanguage();
    const navigate = useNavigate();
    const { setUser } = useAuthStore();

    // Login type state
    const [loginType, setLoginType] = useState<LoginType>('admin');

    const [showPassword, setShowPassword] = useState(false);
    const [rememberMe, setRememberMe] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const [fieldErrors, setFieldErrors] = useState<{ email?: string; password?: string }>({});

    const [formData, setFormData] = useState({
        email: '',
        password: '',
    });

    // Content based on login type
    const loginContent = {
        admin: {
            icon: Shield,
            title: 'لوحة التحكم',
            subtitle: 'تسجيل دخول المسؤولين فقط',
            placeholder: 'admin@subol.edu',
            buttonText: 'تسجيل الدخول',
            loadingText: 'جاري تسجيل الدخول...',
            accentColor: 'bg-brand-primary', // Fallback if tailored unavailable
            gradient: 'from-slate-800 to-slate-900',
        },
        teacher: {
            icon: GraduationCap,
            title: 'بوابة المعلم',
            subtitle: 'للمعلمين المسجلين فقط',
            placeholder: 'teacher@subol.edu',
            buttonText: 'تسجيل الدخول',
            loadingText: 'جاري تسجيل الدخول...',
            accentColor: 'bg-[#AF0C15]',
            gradient: 'from-[#AF0C15] to-[#8B0A11]',
        },
    };

    const currentContent = loginContent[loginType];
    const IconComponent = currentContent.icon;

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Custom validation
        const errors: { email?: string; password?: string } = {};

        if (!formData.email) {
            errors.email = 'البريد الإلكتروني مطلوب';
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
            errors.email = 'يرجى إدخال بريد إلكتروني صحيح';
        }

        if (!formData.password) {
            errors.password = 'كلمة المرور مطلوبة';
        }

        if (Object.keys(errors).length > 0) {
            setFieldErrors(errors);
            return;
        }

        setIsLoading(true);
        setError('');

        try {
            if (loginType === 'admin') {
                // Admin login flow
                const response = await adminService.login({
                    email: formData.email,
                    password: formData.password,
                });

                if (response.token && response.data) {
                    const adminUser = {
                        ...response.data,
                        role: 'admin' as const,
                    };
                    setUser(adminUser as any);
                    navigate(ROUTES.ADMIN_DASHBOARD);
                }
            } else {
                // Teacher login flow
                const response = await teacherAuthService.login({
                    email: formData.email,
                    password: formData.password,
                    remember_me: rememberMe,
                });

                if (response.success && response.data?.teacher) {
                    const teacher = response.data.teacher;

                    // Check if verification is required (OTP auto-generated by backend)
                    if (response.data.requires_verification) {
                        navigate(ROUTES.TEACHER_VERIFY_EMAIL, {
                            state: { email: formData.email }
                        });
                        return;
                    }

                    // Set teacher user
                    const teacherUser = {
                        ...teacher,
                        role: 'teacher' as const,
                    };
                    setUser(teacherUser as any);
                    navigate(ROUTES.TEACHER_DASHBOARD);
                }
            }
        } catch (err: any) {
            const errorMsg = err.response?.data?.message || err.message || '';

            if (errorMsg.includes('Invalid credentials') || err.response?.status === 401) {
                setError('البريد الإلكتروني أو كلمة المرور غير صحيحة');
            } else if (err.response?.data?.message) {
                setError(err.response.data.message);
            } else {
                setError('حدث خطأ. يرجى المحاولة مرة أخرى');
            }
        } finally {
            setIsLoading(false);
        }
    };

    const handleChange = (field: string, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
        setError('');
        setFieldErrors(prev => ({ ...prev, [field]: undefined }));
    };

    const handleLoginTypeChange = (type: LoginType) => {
        setLoginType(type);
        setError('');
        setFieldErrors({});
    };

    return (
        <div
            className="min-h-screen flex items-center justify-center p-6 relative overflow-hidden bg-slate-50 font-sans"
            dir={isRTL ? 'rtl' : 'ltr'}
        >
            {/* Background Decor - Subtle Organic Blobs */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <div className="absolute top-0 right-0 w-full h-[500px] bg-gradient-to-b from-red-50/50 to-transparent opacity-60" />
                <div className="absolute -top-[20%] -right-[10%] w-[600px] h-[600px] rounded-full bg-red-100/30 blur-3xl" />
                <div className="absolute top-[40%] -left-[10%] w-[500px] h-[500px] rounded-full bg-slate-200/40 blur-3xl" />
            </div>

            {/* Main Container */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, ease: "easeOut" }}
                className="relative w-full max-w-[420px] z-10"
            >
                {/* Logo Area */}
                <div className="flex justify-center mb-8">
                    <div className="h-16 w-16 bg-white rounded-2xl shadow-xl shadow-red-900/5 flex items-center justify-center border border-red-50">
                        {/* Placeholder for Logo - using Icon for now */}
                        <Shield className="text-[#AF0C15]" size={32} />
                    </div>
                </div>

                <div className="bg-white rounded-[2rem] shadow-[0_20px_50px_-12px_rgba(0,0,0,0.08)] border border-slate-100 p-8 md:p-10 relative overflow-hidden">
                    {/* Top Accent Line */}
                    <div className={`absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r ${loginType === 'admin' ? 'from-slate-700 to-slate-900' : 'from-[#AF0C15] to-[#8B0A11]'
                        }`} />

                    {/* Header */}
                    <div className="text-center mb-8">
                        <h1 className="text-2xl font-bold text-slate-900 mb-2">
                            {loginType === 'admin' ? 'تسجيل دخول المسؤول' : 'تسجيل دخول المعلم'}
                        </h1>
                        <p className="text-slate-500 text-sm">
                            {currentContent.subtitle}
                        </p>
                    </div>

                    {/* Login Type Toggle */}
                    <div className="bg-slate-100/80 p-1 rounded-xl flex mb-8 relative">
                        {/* Sliding Background */}
                        <motion.div
                            className="absolute top-1 bottom-1 w-[calc(50%-4px)] bg-white rounded-lg shadow-sm"
                            initial={false}
                            animate={{
                                x: isRTL
                                    ? (loginType === 'admin' ? 0 : '100%') // RTL logic
                                    : (loginType === 'admin' ? 0 : '100%'), // LTR logic (adjust based on button order)
                                // Actually, simpler to just use layoutId if items are keyed, but let's do conditional class for simplicity or absolute positioning
                                // Let's simplify: simple conditional classes are robust.
                            }}
                            style={{
                                right: isRTL ? (loginType === 'admin' ? '4px' : 'calc(50% + 0px)') : 'auto',
                                left: isRTL ? 'auto' : (loginType === 'admin' ? '4px' : 'calc(50% + 0px)'),
                            }}
                            layoutId="activeTab"
                        />

                        <button
                            type="button"
                            onClick={() => handleLoginTypeChange('admin')}
                            className={`flex-1 py-2.5 text-sm font-semibold rounded-lg relative z-10 transition-colors duration-300 flex items-center justify-center gap-2 ${loginType === 'admin' ? 'text-slate-900' : 'text-slate-500 hover:text-slate-700'
                                }`}
                        >
                            <Shield size={16} />
                            <span>المسؤول</span>
                        </button>
                        <button
                            type="button"
                            onClick={() => handleLoginTypeChange('teacher')}
                            className={`flex-1 py-2.5 text-sm font-semibold rounded-lg relative z-10 transition-colors duration-300 flex items-center justify-center gap-2 ${loginType === 'teacher' ? 'text-[#AF0C15]' : 'text-slate-500 hover:text-slate-700'
                                }`}
                        >
                            <GraduationCap size={16} />
                            <span>المعلم</span>
                        </button>
                    </div>

                    {/* Error Message */}
                    <AnimatePresence mode='wait'>
                        {error && (
                            <motion.div
                                initial={{ opacity: 0, height: 0 }}
                                animate={{ opacity: 1, height: 'auto' }}
                                exit={{ opacity: 0, height: 0 }}
                                className="mb-6 overflow-hidden"
                            >
                                <div className="bg-red-50 border border-red-100 rounded-xl p-4 flex items-start gap-3">
                                    <AlertCircle size={18} className="text-red-500 mt-0.5 flex-shrink-0" />
                                    <p className="text-red-600 text-sm leading-relaxed">{error}</p>
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>

                    {/* Form */}
                    <form onSubmit={handleSubmit} className="space-y-5" noValidate>
                        {/* Email Input */}
                        <div className="space-y-1.5">
                            <label className="text-sm font-semibold text-slate-700 block">
                                البريد الإلكتروني
                            </label>
                            <div className="relative group">
                                <input
                                    type="email"
                                    value={formData.email}
                                    onChange={(e) => handleChange('email', e.target.value)}
                                    className={`
                                        w-full h-12 px-11 rounded-xl text-slate-900 placeholder:text-slate-400
                                        bg-slate-50 border transition-all duration-200 outline-none
                                        focus:bg-white focus:shadow-[0_0_0_4px_rgba(175,12,21,0.05)]
                                        ${fieldErrors.email
                                            ? 'border-red-300 focus:border-red-500'
                                            : 'border-slate-200 focus:border-[#AF0C15] group-hover:border-slate-300'
                                        }
                                    `}
                                    placeholder={currentContent.placeholder}
                                    dir="ltr"
                                />
                                <div className={`absolute top-1/2 -translate-y-1/2 ${isRTL ? 'right-3.5' : 'left-3.5'} pointer-events-none transition-colors duration-200 ${fieldErrors.email ? 'text-red-400' : 'text-slate-400 group-focus-within:text-[#AF0C15]'
                                    }`}>
                                    <Mail size={20} />
                                </div>
                            </div>
                            {fieldErrors.email && (
                                <p className="text-red-500 text-xs mt-1">{fieldErrors.email}</p>
                            )}
                        </div>

                        {/* Password Input */}
                        <div className="space-y-1.5">
                            <div className="flex justify-between items-center">
                                <label className="text-sm font-semibold text-slate-700 block">
                                    كلمة المرور
                                </label>
                                {loginType === 'teacher' && (
                                    <button
                                        type="button"
                                        onClick={() => navigate(ROUTES.TEACHER_FORGOT_PASSWORD, { state: { email: formData.email } })}
                                        className="text-xs font-semibold text-[#AF0C15] hover:text-[#8B0A11] transition-colors"
                                    >
                                        نسيت كلمة المرور؟
                                    </button>
                                )}
                            </div>
                            <div className="relative group">
                                <input
                                    type={showPassword ? 'text' : 'password'}
                                    value={formData.password}
                                    onChange={(e) => handleChange('password', e.target.value)}
                                    className={`
                                        w-full h-12 px-11 rounded-xl text-slate-900 placeholder:text-slate-400
                                        bg-slate-50 border transition-all duration-200 outline-none
                                        focus:bg-white focus:shadow-[0_0_0_4px_rgba(175,12,21,0.05)]
                                        ${fieldErrors.password
                                            ? 'border-red-300 focus:border-red-500'
                                            : 'border-slate-200 focus:border-[#AF0C15] group-hover:border-slate-300'
                                        }
                                    `}
                                    placeholder="••••••••"
                                    dir="ltr"
                                />
                                <div className={`absolute top-1/2 -translate-y-1/2 ${isRTL ? 'right-3.5' : 'left-3.5'} pointer-events-none transition-colors duration-200 ${fieldErrors.password ? 'text-red-400' : 'text-slate-400 group-focus-within:text-[#AF0C15]'
                                    }`}>
                                    <Lock size={20} />
                                </div>
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className={`absolute top-1/2 -translate-y-1/2 ${isRTL ? 'left-3.5' : 'right-3.5'} text-slate-400 hover:text-slate-600 transition-colors`}
                                >
                                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                </button>
                            </div>
                            {fieldErrors.password && (
                                <p className="text-red-500 text-xs mt-1">{fieldErrors.password}</p>
                            )}
                        </div>

                        {/* Remember Me */}
                        <div className="flex items-center">
                            <label className="flex items-center gap-2 cursor-pointer group select-none">
                                <div className={`w-5 h-5 rounded border flex items-center justify-center transition-all duration-200 ${rememberMe
                                    ? 'bg-[#AF0C15] border-[#AF0C15]'
                                    : 'bg-white border-slate-300 group-hover:border-[#AF0C15]'
                                    }`}>
                                    <input
                                        type="checkbox"
                                        className="sr-only"
                                        checked={rememberMe}
                                        onChange={(e) => setRememberMe(e.target.checked)}
                                    />
                                    {rememberMe && <CheckCircle2 size={12} className="text-white" />}
                                </div>
                                <span className="text-sm text-slate-600 group-hover:text-slate-800 transition-colors">
                                    تذكرني
                                </span>
                            </label>
                        </div>

                        {/* Submit Button */}
                        <button
                            type="submit"
                            disabled={isLoading}
                            className={`
                                w-full h-12 rounded-xl font-bold text-white shadow-lg shadow-red-900/10
                                transition-all duration-300 flex items-center justify-center gap-2
                                ${isLoading ? 'opacity-80 cursor-wait' : 'hover:scale-[1.02] hover:shadow-xl hover:shadow-red-900/20 active:scale-[0.98]'}
                            `}
                            style={{
                                background: loginType === 'admin'
                                    ? 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)'
                                    : 'linear-gradient(135deg, #AF0C15 0%, #8B0A11 100%)'
                            }}
                        >
                            {isLoading ? (
                                <>
                                    <svg className="animate-spin h-5 w-5 text-white/90" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                    </svg>
                                    <span>{currentContent.loadingText}</span>
                                </>
                            ) : (
                                <>
                                    <span>{currentContent.buttonText}</span>
                                    <ArrowLeft size={20} className={isRTL ? 'rotate-180' : ''} />
                                </>
                            )}
                        </button>
                    </form>

                    <div className="mt-8 pt-6 border-t border-slate-100 text-center">
                        <p className="text-slate-400 text-xs">
                            © 2024 سُبُل - جميع الحقوق محفوظة
                        </p>
                    </div>

                </div>
            </motion.div>
        </div>
    );
}
