import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useLanguage } from '../../hooks';
import { useAuthStore } from '../../store';
import { AuthNavbar } from '../../components';
import { ROUTES } from '../../../shared/constants';
import { authService } from '../../../data/api';
import { teacherAuthService } from '../../../data/api/teacherAuthService';

// Lucide Icons
import {
    Mail,
    Lock,
    Eye,
    EyeOff,
    GraduationCap,
    Users,
    BadgeCheck,
    CheckCircle,
    TrendingUp,
    ArrowLeft,
    School,

} from 'lucide-react';

import { SessionConflictModal } from '../../components/auth/SessionConflictModal';
import { OtpVerificationModal } from '../../components/auth/OtpVerificationModal';

type UserType = 'student' | 'parent' | 'teacher';



export function SignInPage() {
    const { isRTL } = useLanguage();
    const navigate = useNavigate();
    const { setUser } = useAuthStore();

    const [userType, setUserType] = useState<UserType>('student');
    const [showPassword, setShowPassword] = useState(false);
    const [rememberMe, setRememberMe] = useState(false);
    const [isLoading, setIsLoading] = useState(false);

    const [showConflictModal, setShowConflictModal] = useState(false);
    const [showOtpModal, setShowOtpModal] = useState(false);
    const [otpError, setOtpError] = useState('');
    const [isForceLoginLoading, setIsForceLoginLoading] = useState(false);
    const [isOtpLoading, setIsOtpLoading] = useState(false);
    const [error, setError] = useState('');
    const [fieldErrors, setFieldErrors] = useState<{ email?: string; password?: string }>({});

    const [formData, setFormData] = useState({
        email: '',
        password: '',
    });

    const handleLogin = async (forceLogin = false, otp?: string) => {
        if (otp) {
            setIsOtpLoading(true);
            setOtpError('');
        } else if (forceLogin) {
            setIsForceLoginLoading(true);
        } else {
            setIsLoading(true);
        }

        // Don't clear main error if we are in OTP modal context, unless it's a fresh login attempt
        if (!otp) {
            setError('');
        }

        try {
            let response;
            const loginData = {
                email: formData.email,
                password: formData.password,
                force_login: forceLogin,
                otp: otp
            };

            if (userType === 'student') {
                response = await authService.studentLogin(loginData);
            } else if (userType === 'parent') {
                response = await authService.parentLogin(loginData);
            } else {
                response = await teacherAuthService.login({
                    ...loginData,
                    remember_me: rememberMe,
                });
            }

            if (response.success && response.data) {
                const data = response.data as any;

                // Special handling for teacher login
                if (userType === 'teacher') {
                    // Check if verification is required (OTP auto-generated by backend)
                    if (data.requires_verification) {
                        navigate(ROUTES.TEACHER_VERIFY_EMAIL, {
                            state: { email: formData.email }
                        });
                        return;
                    }

                    const userData = data.teacher;
                    if (userData) {
                        const userWithRole = {
                            ...userData,
                            role: 'teacher',
                        };
                        setUser(userWithRole as any);

                        // Pre-warm teacher chunks so navigation is instant
                        await Promise.allSettled([
                            import('../../components/teacher'),
                            import('../teacher/TeacherDashboardPage'),
                        ]);
                        navigate(ROUTES.TEACHER_DASHBOARD);
                    }
                    return;
                }

                // Student and Parent login flow
                const userData = data.student || data.parent;

                if (userData) {
                    // Check if email is verified
                    const isEmailVerified = userData.email_verified_at && userData.email_verified_at !== '';

                    if (!isEmailVerified) {
                        navigate(ROUTES.VERIFY_EMAIL, {
                            state: { email: formData.email, userType }
                        });
                        return;
                    }

                    // Add role based on userType for session management
                    const userWithRole = {
                        ...userData,
                        role: userType as 'student' | 'parent',
                    };

                    setUser(userWithRole as any);

                    // Pre-warm the destination chunks BEFORE navigating
                    // so React Router's transition resolves instantly
                    if (userType === 'student') {
                        await Promise.allSettled([
                            import('../dashboard/StudentLayout'),
                            import('../dashboard/StudentHomePage'),
                        ]);
                        navigate(ROUTES.DASHBOARD);
                    } else if (userType === 'parent') {
                        await Promise.allSettled([
                            import('../dashboard/ParentLayout'),
                            import('../dashboard/ParentHomePage'),
                        ]);
                        navigate(ROUTES.PARENT_DASHBOARD);
                    }
                }
            }
        } catch (err: any) {
            // Extract Arabic message from API response if available
            const apiResponse = err.response?.data;
            const arabicMessage = apiResponse?.message_ar;
            const errorCode = apiResponse?.error_code;

            if (errorCode === 'active_session_exists') {
                setShowConflictModal(true);
                return; // Stop further error handling
            }

            if (errorCode === 'otp_required') {
                setShowConflictModal(false);
                setShowOtpModal(true);
                // Clear any previous OTP errors when showing modal for the first time
                if (!otp) setOtpError('');
                return;
            }

            if (errorCode === 'invalid_otp') {
                setOtpError(arabicMessage || 'رمز التحقق غير صحيح. يرجى المحاولة مرة أخرى.');
                return;
            }

            if (errorCode === 'email_not_verified') {
                if (userType === 'teacher') {
                    navigate(ROUTES.TEACHER_VERIFY_EMAIL, {
                        state: { email: formData.email }
                    });
                } else {
                    // Email not verified, redirect to verification page
                    setError(arabicMessage || 'البريد الإلكتروني غير مفعل. يرجى التحقق من بريدك الإلكتروني أولاً.');
                    setTimeout(() => {
                        navigate(ROUTES.VERIFY_EMAIL, {
                            state: { email: formData.email, userType }
                        });
                    }, 2000);
                }
            } else if (errorCode === 'invalid_credentials') {
                const debugMsg = apiResponse?.debug_error ? ` (${apiResponse.debug_error})` : '';
                setError((arabicMessage || 'البريد الإلكتروني أو كلمة المرور غير صحيحة') + debugMsg);
            } else if (arabicMessage) {
                setError(arabicMessage);
            } else if (err.message?.includes('verify your email')) {
                setError('يرجى التحقق من بريدك الإلكتروني أولاً');
            } else if (err.message?.includes('Invalid credentials')) {
                setError('البريد الإلكتروني أو كلمة المرور غير صحيحة');
            } else if (!showOtpModal) {
                // Only show main form error if OTP modal is not open
                setError(err.response?.data?.message || 'حدث خطأ. يرجى المحاولة مرة أخرى');
                // Handle OTP specific errors that weren't caught by specific error codes above
            } else if (otp || showOtpModal) {
                setOtpError(arabicMessage || err.response?.data?.message || 'رمز التحقق غير صحيح');
            }

            // Clear loading on error paths — spinner stays visible on success
            // because startTransition holds this page while the destination loads.
            setIsLoading(false);
            setIsForceLoginLoading(false);
            setIsOtpLoading(false);
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Custom validation
        const errors: { email?: string; password?: string } = {};

        if (!formData.email) {
            errors.email = 'البريد الإلكتروني مطلوب';
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
            errors.email = 'يرجى إدخال بريد إلكتروني صحيح';
        }

        if (!formData.password) {
            errors.password = 'كلمة المرور مطلوبة';
        }

        if (Object.keys(errors).length > 0) {
            setFieldErrors(errors);
            return;
        }

        await handleLogin(false);
    };

    const handleChange = (field: string, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
        setError('');
        setFieldErrors(prev => ({ ...prev, [field]: undefined }));
    };

    const handleForceLogin = async () => {
        await handleLogin(true);
        // Modal closing is handled in handleLogin based on response (e.g. if success or otp_required)
    };

    const handleOtpSubmit = async (otp: string) => {
        await handleLogin(true, otp);
    };

    const handleOtpResend = async () => {
        // Resend is essentially trying to force login again without OTP, which triggers generation
        await handleLogin(true);
    };

    return (
        <div className="min-h-screen bg-soft-cloud" dir={isRTL ? 'rtl' : 'ltr'}>
            <AuthNavbar />

            <div className="pt-[72px] min-h-screen grid lg:grid-cols-2">
                {/* Form Section - Order 2 on desktop makes it appear on RIGHT in RTL */}
                <div className="flex items-center justify-center px-4 py-6 sm:p-8 lg:order-2">
                    <div className="w-full max-w-[420px]">
                        {/* Logo */}
                        <div
                            className="flex items-center gap-2 mb-6 sm:mb-10 justify-center lg:justify-start cursor-pointer select-none"
                            onDoubleClick={() => navigate(ROUTES.ADMIN_LOGIN)}
                        >
                            <img src="/images/subol-red.png" alt="سُبُل" className="w-7 h-7 sm:w-8 sm:h-8 lg:w-9 lg:h-9" />
                            <span className="text-xl sm:text-2xl lg:text-3xl font-extrabold text-shibl-crimson">سُبُل</span>
                        </div>

                        {/* Header */}
                        <div className="mb-5 sm:mb-8 text-center lg:text-right">
                            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-extrabold text-charcoal mb-2 sm:mb-3">تسجيل الدخول</h1>
                            <p className="text-sm sm:text-base text-slate-grey">أهلاً بك! يرجى إدخال بياناتك للمتابعة.</p>
                        </div>

                        {/* Error Message */}
                        {error && (
                            <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-center text-sm">
                                {error}
                            </div>
                        )}
                        {/* Tabs */}
                        <div className="flex bg-slate-100/50 p-1 sm:p-1.5 rounded-xl sm:rounded-2xl mb-5 sm:mb-8">
                            <button
                                className={`flex-1 flex items-center justify-center gap-1.5 sm:gap-2 py-2.5 sm:py-3 px-2 sm:px-4 rounded-lg sm:rounded-xl font-bold text-xs sm:text-sm transition-all duration-300 ${userType === 'student'
                                    ? 'bg-white text-shibl-crimson shadow-md shadow-shibl-crimson/10'
                                    : 'text-slate-grey hover:text-charcoal hover:bg-slate-50'
                                    }`}
                                onClick={() => setUserType('student')}
                            >
                                <GraduationCap size={18} className="sm:w-5 sm:h-5" />
                                <span>طالب</span>
                            </button>
                            <button
                                className={`flex-1 flex items-center justify-center gap-1.5 sm:gap-2 py-2.5 sm:py-3 px-2 sm:px-4 rounded-lg sm:rounded-xl font-bold text-xs sm:text-sm transition-all duration-300 ${userType === 'parent'
                                    ? 'bg-white text-shibl-crimson shadow-md shadow-shibl-crimson/10'
                                    : 'text-slate-grey hover:text-charcoal hover:bg-slate-50'
                                    }`}
                                onClick={() => setUserType('parent')}
                            >
                                <Users size={18} className="sm:w-5 sm:h-5" />
                                <span>ولي أمر</span>
                            </button>
                            <button
                                className={`flex-1 flex items-center justify-center gap-1.5 sm:gap-2 py-2.5 sm:py-3 px-2 sm:px-4 rounded-lg sm:rounded-xl font-bold text-xs sm:text-sm transition-all duration-300 ${userType === 'teacher'
                                    ? 'bg-white text-shibl-crimson shadow-md shadow-shibl-crimson/10'
                                    : 'text-slate-grey hover:text-charcoal hover:bg-slate-50'
                                    }`}
                                onClick={() => setUserType('teacher')}
                            >
                                <School size={18} className="sm:w-5 sm:h-5" />
                                <span>معلم</span>
                            </button>
                        </div>

                        {/* Form */}
                        <form onSubmit={handleSubmit} className="flex flex-col gap-4 sm:gap-5" noValidate>
                            {/* Email */}
                            <div className="form-control w-full">
                                <label className="label pb-1">
                                    <span className="label-text font-bold text-slate-700">البريد الإلكتروني</span>
                                </label>
                                <div className="relative">
                                    <input
                                        type="email"
                                        placeholder="name@example.com"
                                        className={`input-pro peer pr-12 ${fieldErrors.email ? 'input-pro-error' : ''}`}
                                        value={formData.email}
                                        onChange={(e) => handleChange('email', e.target.value)}
                                        dir="rtl"
                                        autoComplete="email"
                                    />
                                    <Mail size={20} className={`absolute right-4 top-1/2 -translate-y-1/2 transition-all duration-300 ${fieldErrors.email ? 'text-red-400' : 'text-slate-400 peer-focus:text-shibl-crimson peer-focus:scale-110'}`} />
                                </div>
                                {fieldErrors.email && (
                                    <p className="text-red-500 text-sm mt-1 flex items-center gap-1">
                                        <span>⚠</span> {fieldErrors.email}
                                    </p>
                                )}
                            </div>

                            {/* Password */}
                            <div className="form-control w-full">
                                <label className="label pb-1 flex justify-between">
                                    <span className="label-text font-bold text-slate-700">كلمة المرور</span>
                                    <Link to={ROUTES.FORGOT_PASSWORD} className="text-sm font-bold text-shibl-crimson hover:underline">نسيت كلمة المرور؟</Link>
                                </label>
                                <div className="relative">
                                    <input
                                        type={showPassword ? 'text' : 'password'}
                                        placeholder="••••••••"
                                        className={`input-pro peer pr-12 pl-12 ${fieldErrors.password ? 'input-pro-error' : ''}`}
                                        value={formData.password}
                                        onChange={(e) => handleChange('password', e.target.value)}
                                        dir="rtl"
                                        autoComplete="current-password"
                                    />
                                    <Lock size={20} className={`absolute right-4 top-1/2 -translate-y-1/2 transition-all duration-300 ${fieldErrors.password ? 'text-red-400' : 'text-slate-400 peer-focus:text-shibl-crimson peer-focus:scale-110'}`} />
                                    <button
                                        type="button"
                                        className="absolute left-3 top-1/2 -translate-y-1/2 p-1 text-slate-400 hover:text-shibl-crimson"
                                        onClick={() => setShowPassword(!showPassword)}
                                    >
                                        {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                    </button>
                                </div>
                                {fieldErrors.password && (
                                    <p className="text-red-500 text-sm mt-1 flex items-center gap-1">
                                        <span>⚠</span> {fieldErrors.password}
                                    </p>
                                )}
                            </div>

                            {/* Remember Me */}
                            <div className="form-control">
                                <label className="label cursor-pointer justify-start gap-3">
                                    <input
                                        type="checkbox"
                                        className="checkbox checkbox-primary checkbox-sm"
                                        checked={rememberMe}
                                        onChange={(e) => setRememberMe(e.target.checked)}
                                    />
                                    <span className="label-text text-slate-600">تذكرني لاحقاً</span>
                                </label>
                            </div>

                            {/* Submit Button */}
                            <button
                                type="submit"
                                className="btn-primary-pro w-full gap-3"
                                disabled={isLoading}
                            >
                                {isLoading ? (
                                    <span className="loading loading-spinner"></span>
                                ) : (
                                    <>
                                        <span>تسجيل الدخول</span>
                                        <ArrowLeft size={20} style={{ transform: isRTL ? 'rotate(180deg)' : 'none' }} />
                                    </>
                                )}
                            </button>
                        </form>

                        <p className="mt-5 sm:mt-8 text-center text-sm sm:text-base text-slate-grey">
                            ليس لديك حساب؟{' '}
                            <Link to={ROUTES.REGISTER} className="text-shibl-crimson font-bold hover:underline">أنشئ حساباً الآن</Link>
                        </p>


                    </div>
                </div>

                {/* Visual Section - Order 1 on desktop makes it appear on LEFT in RTL */}
                <div className="hidden lg:flex items-center justify-center bg-gradient-to-br from-red-50 via-rose-50 to-orange-50 p-12 relative overflow-hidden lg:order-1">
                    {/* Floating Card - Top Left (corner, in empty space) */}
                    <div className="absolute top-8 left-8 floating-card-success p-4 flex items-center gap-3 animate-float z-10">
                        <div className="w-11 h-11 bg-white/20 rounded-xl flex items-center justify-center">
                            <CheckCircle size={24} className="text-white" />
                        </div>
                        <div className="flex flex-col">
                            <span className="text-white font-bold text-sm">تم تسجيل الحضور</span>
                            <span className="text-white/80 text-xs">حصة الرياضيات اليوم</span>
                        </div>
                    </div>

                    <div className="relative w-full max-w-lg flex flex-col items-center gap-8">
                        {/* Main Image - Changes based on user type */}
                        <div className="relative w-full max-w-[380px]">
                            <img
                                src={userType === 'student' ? '/images/signin-student.webp' : userType === 'parent' ? '/images/signin-parent.webp' : '/images/hero-teacher.webp'}
                                alt={userType === 'student' ? 'طالب' : userType === 'parent' ? 'ولي أمر' : 'معلم'}
                                className="w-full h-auto rounded-3xl drop-shadow-2xl transition-all duration-500"
                                fetchPriority="high"
                            />
                        </div>

                        {/* Caption - Changes based on user type */}
                        <div className="text-center mt-4">
                            <h2 className="text-2xl font-extrabold text-charcoal mb-2">
                                {userType === 'student' ? 'مرحباً بك مجدداً' : userType === 'parent' ? 'مرحباً ولي الأمر' : 'مرحباً أيها المعلم'}
                            </h2>
                            <p className="text-slate-grey max-w-sm">
                                {userType === 'student'
                                    ? 'تابع رحلتك التعليمية واستمتع بأفضل تجربة تعلم تفاعلية.'
                                    : userType === 'parent'
                                        ? 'تابع تقدم أبنائك واحصل على تقارير مفصلة عن أدائهم.'
                                        : 'قم بإدارة فصولك الدراسية وتفاعل مع طلابك بسهولة.'}
                            </p>
                        </div>
                    </div>

                    {/* Floating Card - Bottom Right (corner, in empty space) */}
                    <div className="absolute bottom-8 right-8 floating-card p-5 flex items-center gap-4 animate-float animation-delay-3000 z-10">
                        <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
                            <TrendingUp size={28} className="text-white" />
                        </div>
                        <div className="flex flex-col">
                            <span className="text-white font-extrabold text-lg">أداء متميز</span>
                            <span className="text-white/80 text-sm">تحسن بنسبة 25% هذا الشهر</span>
                        </div>
                    </div>
                </div>
            </div>


            {/* Session Conflict Modal */}
            <SessionConflictModal
                isOpen={showConflictModal}
                onClose={() => setShowConflictModal(false)}
                onForceLogin={handleForceLogin}
                isLoading={isForceLoginLoading}
            />

            {/* OTP Verification Modal */}
            <OtpVerificationModal
                isOpen={showOtpModal}
                onClose={() => setShowOtpModal(false)}
                onSubmit={handleOtpSubmit}
                isLoading={isOtpLoading}
                onResend={handleOtpResend}
                error={otpError}
                email={formData.email}
            />
        </div>
    );
}
