import {
    Terminal,
    Server,
    Code,
    Database,
} from 'lucide-react';

export const developers = [
    {
        id: 1,
        slug: "ahmed-azam",
        name: "أحمد عزام",
        role: "قائد الفريق ومطور فلاتر وواجهات أمامية",
        bio: "قائد الفريق ومطور فلاتر خبير يقود تطوير مشروع سُبُل. يركز على إنشاء تطبيقات محمولة عالية الجودة وتنسيق جهود الفريق. يمتلك خبرة ممتازة في تطوير الواجهات الأمامية باستخدام React, Next.js, TS, JS, Tailwind.",
        longBio: "أحمد هو العقل المدبر وراء تجربة المستخدم في منصة سُبُل. بصفته قائد الفريق ومطور فلاتر خبير، يجمع بين الرؤية الفنية والقدرة على التنفيذ بدقة متناهية. يتميز أحمد بقدرته الفائقة على تحويل المتطلبات المعقدة إلى واجهات مستخدم بديهية وجذابة. يمتلك خبرة واسعة تمتد من تطوير تطبيقات الهاتف المحمول باستخدام Flutter إلى بناء تطبيقات الويب الحديثة باستخدام React و Next.js المتقدم. اهتمامه بأدق التفاصيل وشغفه بتقديم أفضل تجربة للمستخدم يجعلانه ركيزة أساسية في الابتكار المستمر لتجربة سُبُل التعليمية.",
        icon: <Terminal size={32} />,
        image_url: "https://i.ibb.co/bMpK8X8Y/Ahmed.png",
        color: "text-shibl-crimson",
        bg: "bg-red-50",
        bgGlass: "bg-white/90",
        delay: 0.1,
        email: "ahmed750@std.mans.edu.eg",
        linkedin: "https://www.linkedin.com/in/ahmed-azam-320a98200",
        github: "https://github.com/Ahmed2300",
        instagram: "https://www.instagram.com/ahmed_a_azam/",
        portfolio: "https://ahmedazamportfolio.netlify.app/",
        skills: ["فلاتر", "دارت", "React", "Next.js", "TypeScript", "Tailwind"]
    },
    {
        id: 2,
        slug: "manar-elnahty",
        name: "منار النحتي",
        role: "مطور فلاتر وواجهات أمامية",
        bio: "مطور فلاتر ومتدرب في ITI متخصص في تطوير تطبيقات الموبايل متعددة المنصات. بالإضافة إلى خبرة ممتازة في تطوير الواجهات الأمامية باستخدام React, Next.js, TS, JS, Tailwind.",
        longBio: "منار مطورة شغوفة ومبدعة، متخصصة في صياغة تجارب رقمية سلسة عبر منصات متعددة. بخلفيتها القوية كمتدربة في معهد تكنولوجيا المعلومات (ITI)، تجمع منار بشكل فريد بين مهارات تطوير تطبيقات الموبايل باستخدام فلاتر وبناء واجهات الويب الأمامية المتقدمة. تمتاز بقدرتها على كتابة كود نظيف وقابل للتطوير باستخدام أحدث التقنيات مثل React و TypeScript. مساهماتها الفعالة تضمن أن تكون واجهة المستخدم لمنصة سُبُل متجاوبة وسريعة وموثوقة لجميع المتعلمين.",
        icon: <Server size={32} />,
        image_url: "https://i.ibb.co/tP36BwQ9/manar.png",
        color: "text-rose-600",
        bg: "bg-rose-50",
        bgGlass: "bg-white/80",
        delay: 0.2,
        email: "manarelnahty@gmail.com",
        linkedin: "https://www.linkedin.com/in/manar-e-6b21bb230",
        github: "https://github.com/manarelnahty",
        instagram: "https://www.instagram.com/manar_elnahty?igsh=M2VxdXRnaDRtMTRm&utm_source=qr",
        skills: ["فلاتر", "دارت", "React", "Next.js", "TypeScript", "Tailwind"]
    },
    {
        id: 3,
        slug: "mohamed-badr",
        name: "محمد بدر",
        role: "مطور فلاتر",
        bio: "مطور فلاتر ومتدرب في تطوير الواجهة الأمامية وتطبيقات الموبايل متعددة المنصات في ITI. شغوف بإنشاء تطبيقات محمولة جميلة وعالية الأداء باستخدام إطار عمل فلاتر.",
        longBio: "محمد هو فنان الكود الذي يركز على تصميم وبناء تطبيقات الموبايل. بفضل تدريبه المتخصص في ITI وشغفه العميق بتجربة المستخدم (UI/UX)، يجلب محمد لمسة من الإبداع لكل واجهة يصممها. يكرس جهده لترجمة التصاميم إلى تطبيقات فلاتر عالية الأداء، مع التأكد من أن كل تفاعل وحركة داخل التطبيق تبدو طبيعية وممتعة للمستخدم. دقة محمد واهتمامه بسرعة الأداء يضمنان تقديم تطبيق جوال لمنصة سُبُل يلبي تطلعات الطلاب والمعلمين على حد سواء.",
        icon: <Code size={32} />,
        image_url: "https://iili.io/KWL2vG1.jpg",
        color: "text-red-700",
        bg: "bg-red-50",
        bgGlass: "bg-white/80",
        delay: 0.3,
        email: "mohamedbadr4iti@gmail.com",
        linkedin: "https://www.linkedin.com/in/mhmdbadr4flutter/",
        github: "https://github.com/mohmdadl",
        instagram: "https://www.instagram.com/mohmd_adl/",
        skills: ["فلاتر", "دارت", "UI/UX"]
    },
    {
        id: 4,
        slug: "ahmed-farghly",
        name: "أحمد فرغلي",
        role: "مهندس واجهات خلفية",
        bio: "مهندس برمجيات متخصص في الواجهات الخلفية باستخدام Django و Laravel. يساهم في بناء أنظمة قوية وقابلة للتطوير لدعم العمليات المعقدة للمنصة بكفاءة عالية.",
        longBio: "أحمد فرغلي هو مهندس النظم المعمارية القوية. يتمتع بخبرة استثنائية في بناء البنى التحتية للمقاييس الكبيرة (Backend) باستخدام إطارات عمل قوية مثل Laravel و Django. لا تتوقف قدرات أحمد عند كتابة الشيفرة، بل تمتد إلى إدارة الخوادم وعمليات التطوير (DevOps)، مما يضمن أن خوادم سُبُل تعمل بكفاءة وبدون أعطال حتى في أوقات الذروة. تصميماته المعمارية للواجهة الخلفية هي الأساس المتين الذي تستند عليه جميع الميزات التعليمية المتقدمة في المنصة.",
        icon: <Server size={32} />,
        image_url: "https://avatars.githubusercontent.com/u/95584009?v=4",
        color: "text-rose-700",
        bg: "bg-rose-50",
        bgGlass: "bg-white/80",
        delay: 0.4,
        email: "ahmedgits2001@gmail.com",
        linkedin: "https://www.linkedin.com/in/ahmed-farghly-879b09257",
        github: "https://github.com/Ahmedfargh",
        skills: ["Laravel", "Django", "Backend", "API", "Golang", "Server Administrator", "DevOps"]
    },
    {
        id: 5,
        slug: "ahmed-essam",
        name: "أحمد عصام",
        role: "مطور واجهات خلفية",
        bio: "مطور واجهات خلفية متخصص في PHP و Laravel. يساهم في بناء هيكلية برمجية متينة وموثوقة، مع التركيز على جودة الأكواد وفعالية الأداء في المشاريع التقنية.",
        longBio: "أحمد عصام هو مهندس المنطق والأداء في الكواليس. يتخصص أحمد في بناء قواعد البيانات وتطوير واجهات برمجة التطبيقات (APIs) المعقدة باستخدام PHP و Laravel. يركز أحمد باستمرار على كتابة أكواد نظيفة، آمنة، وقابلة للاختبار والصيانة. مساهماته أساسية في ضمان تدفق البيانات بأمان وسرعة بين قواعد البيانات وواجهات المستخدم، بالإضافة إلى حل المشكلات التقنية المعقدة لدعم الرؤية المستقبلية للمنصة وميزاتها المتقدمة.",
        icon: <Database size={32} />,
        color: "text-shibl-crimson-dark",
        bg: "bg-red-50",
        bgGlass: "bg-white/80",
        delay: 0.5,
        email: "ahmedessam1.8.14@gmail.com",
        linkedin: "https://www.linkedin.com/in/ahmed-essam-465208232",
        github: "https://github.com/AhmedEssam88",
        skills: ["PHP", "Laravel", "Backend Development", "ASP.NET"]
    }
];
