/**
 * Teacher Authentication Service
 * 
 * Handles all teacher authentication operations including login, registration,
 * email verification, and password management. Follows the same patterns as
 * authService.ts for consistency.
 */

import apiClient, { setTokens, clearTokens } from './ApiClient';
import { endpoints } from './endpoints';

// ==================== TYPES ====================

export interface TeacherLoginRequest {
    email: string;
    password: string;
    remember_me?: boolean;
    force_login?: boolean;
    otp?: string;
}

export interface TeacherRegisterRequest {
    name: string;
    email: string;
    password: string;
    password_confirmation: string;
    is_academic?: boolean; // true = academic teacher, false = skills instructor
}

export interface TeacherVerifyEmailRequest {
    email: string;
    otp: string;
}

export interface TeacherResetPasswordRequest {
    email: string;
    otp: string;
    password: string;
    password_confirmation: string;
}

export interface TeacherChangePasswordRequest {
    old_password: string;
    new_password: string;
    new_password_confirmation: string;
}

export interface TeacherData {
    id: number;
    name: string;
    email: string;
    phone?: string;
    specialization?: string;
    qualification?: string;
    image_path?: string | null;
    status?: string;
    is_academic?: boolean;
    type?: 'teacher' | 'instructor';
    balance?: number;
    hire_date?: string;
    email_verified_at?: string | null;
    created_at?: string;
    updated_at?: string;
}

export interface TeacherAuthResponse {
    success: boolean;
    message?: string;
    data?: {
        teacher?: TeacherData;
        token?: string;
        requires_verification?: boolean;
    };
}

export const teacherAuthService = {
    /**
     * Login teacher with email and password
     * Returns token, teacher data, and requires_verification flag
     * If requires_verification is true, OTP has been auto-generated by backend
     */
    login: async (data: TeacherLoginRequest): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.login, data);

        // Backend returns: { success, message, data: { teacher, token, requires_verification } }
        if (response.data.data?.token) {
            setTokens(response.data.data.token, '');
        }

        return {
            success: response.data.success,
            message: response.data.message,
            data: {
                teacher: response.data.data?.teacher,
                token: response.data.data?.token,
                requires_verification: response.data.data?.requires_verification ?? false,
            },
        };
    },

    /**
     * Register a new teacher account
     * After registration, teacher must verify email via OTP
     */
    register: async (data: TeacherRegisterRequest): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.register, data);

        // Backend returns: { success, message, data: { teacher, token } }
        // Token is returned but email is not verified yet
        if (response.data.data?.token) {
            setTokens(response.data.data.token, '');
        }

        return {
            success: response.data.success,
            message: response.data.message,
            data: {
                teacher: response.data.data?.teacher,
                token: response.data.data?.token,
            },
        };
    },

    /**
     * Verify teacher email with OTP code
     * On success, teacher is fully authenticated
     */
    verifyEmail: async (data: TeacherVerifyEmailRequest): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.verifyEmail, data);

        // Backend returns: { success, message, data: { teacher, token } }
        if (response.data.data?.token) {
            setTokens(response.data.data.token, '');
        }

        return {
            success: response.data.success,
            message: response.data.message,
            data: {
                teacher: response.data.data?.teacher,
                token: response.data.data?.token,
            },
        };
    },

    /**
     * Resend OTP to teacher's email
     * Used when OTP expires or wasn't received
     */
    resendOtp: async (email: string): Promise<TeacherAuthResponse> => {
        // Note: Backend may not have a dedicated resend-otp endpoint for teachers
        // If not, this should trigger the forgot-password or a similar flow
        const response = await apiClient.post(endpoints.teacherAuth.resendOtp, { email });

        return {
            success: response.data.success ?? true,
            message: response.data.message ?? 'OTP sent successfully',
        };
    },

    /**
     * Request password reset - sends OTP to email
     */
    forgotPassword: async (email: string): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.forgotPassword, { email });

        return {
            success: response.data.success ?? true,
            message: response.data.message ?? 'OTP sent to your email',
        };
    },

    /**
     * Reset password using OTP
     */
    resetPassword: async (data: TeacherResetPasswordRequest): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.resetPassword, data);

        return {
            success: response.data.success ?? true,
            message: response.data.message ?? 'Password reset successfully',
        };
    },

    /**
     * Change password for authenticated teacher
     */
    changePassword: async (data: TeacherChangePasswordRequest): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.changePassword, data);

        return {
            success: response.data.success ?? true,
            message: response.data.message ?? 'Password changed successfully',
        };
    },

    /**
     * Get current authenticated teacher profile
     */
    getMe: async (): Promise<TeacherAuthResponse> => {
        const response = await apiClient.get(endpoints.teacherAuth.me);

        return {
            success: response.data.success ?? true,
            message: response.data.message,
            data: {
                teacher: response.data.data ?? response.data,
            },
        };
    },

    /**
     * Update authenticated teacher's profile
     */
    updateProfile: async (data: {
        name?: string;
        phone?: string;
        specialization?: string;
        qualification?: string;
        image?: File;
    }): Promise<TeacherAuthResponse> => {
        const formData = new FormData();

        if (data.name) formData.append('name', data.name);
        if (data.phone) formData.append('phone', data.phone);
        if (data.specialization) formData.append('specialization', data.specialization);
        if (data.qualification) formData.append('qualification', data.qualification);
        if (data.image) formData.append('image', data.image);

        // Laravel requires _method for PUT/PATCH when using FormData with files
        formData.append('_method', 'PUT');

        const response = await apiClient.post(endpoints.teacherAuth.updateProfile, formData, {
            headers: { 'Content-Type': 'multipart/form-data' },
        });

        return {
            success: response.data.success ?? true,
            message: response.data.message ?? 'Profile updated successfully',
            data: {
                teacher: response.data.data ?? response.data,
            },
        };
    },

    /**
     * Refresh authentication token
     */
    refreshToken: async (): Promise<TeacherAuthResponse> => {
        const response = await apiClient.post(endpoints.teacherAuth.refresh);

        if (response.data.data?.token) {
            setTokens(response.data.data.token, '');
        }

        return {
            success: response.data.success ?? true,
            message: response.data.message,
            data: {
                teacher: response.data.data?.teacher,
                token: response.data.data?.token,
            },
        };
    },

    /**
     * Logout current session (revoke current token)
     */
    logout: async (): Promise<void> => {
        await apiClient.post(endpoints.teacherAuth.logout);
        clearTokens();
    },

    /**
     * Logout from all devices (revoke all tokens)
     */
    logoutAll: async (): Promise<void> => {
        await apiClient.post(endpoints.teacherAuth.logoutAll);
        clearTokens();
    },
};

export default teacherAuthService;
