export { TeacherDashboardPage } from './TeacherDashboardPage';
export { TeacherCoursesPage } from './TeacherCoursesPage';
export { TeacherQuizzesPage } from './TeacherQuizzesPage';
export { TeacherSettingsPage } from './TeacherSettingsPage';
export { TeacherTimeSlotsPage } from './TeacherTimeSlotsPage';
export { TeacherCourseDetailsPage } from './TeacherCourseDetailsPage';
export { TeacherAnalyticsPage } from './AnalyticsPage';
export { default as TeacherRecordingsPage } from './TeacherRecordingsPage';
export { TeacherSlotRequestsPage } from './TeacherSlotRequestsPage';
export { default as TeacherWeeklySchedulePage } from './TeacherWeeklySchedulePage';
